### ISSUE TITLE
crash on video recording on android lolipop 

### ISSUE THREAD

**Issue by usamakhan049** [alhazmy13/MediaPicker#35]
Application is crashing when i try to record video

**Comment by davidarshavsky** [comment]
Usually happens on OS 5

**Comment by alhazmy13** [comment]
Is it on real device or emulator?

**Comment by alhazmy13** [comment]
it should be fixed with version `2.3.3` 
Thanks

**Comment by davidarshavsky** [comment]
It was on real device Samsung s5 Os 5.0.1
On OS 6+ its working good, only on older version it crashing when start recording and trying to upload.

**Comment by alhazmy13** [comment]
Hi @davidarshavsky 
Can you check if the issue solved with version `2.3.3` ?
Thanks

**Comment by davidarshavsky** [comment]
I will check it and let you know, thanks.

**Comment by PitipongXYZ** [comment]
It still crashes with version 2.3.3 even 2.4.0 on an Android 4.4

Thanks.
